#include "field_shader.h"

const char* field_shader_vs = ""
  "#version 330 core\n"
  "layout (location = 0) in vec2 aPos;\n"
  "  \n"
  "\n"
  "out vec2 tc;\n"
  "\n"
  "uniform vec2 position;\n"
  "uniform float scale;\n"
  "\n"
  "uniform vec2 localPos;\n"
  "uniform float rotation;\n"
  "\n"
  "uniform float aspectRatio;\n"
  "\n"
  "\n"
  "void main()\n"
  "{\n"
  "    vec2 pos1 = vec2(aPos.x * scale,aPos.y * scale) + localPos;\n"
  "    float sz = sin(rotation);\n"
  "    float cz = cos(rotation);\n"
  "\n"
  "    float x = pos1.x * cz - pos1.y * sz;\n"
  "    float y = pos1.y * cz + pos1.x * sz;\n"
  "\n"
  "    vec2 pos = vec2(x, y) + position; \n"
  "\n"
  "    pos = vec2(pos.x / aspectRatio, pos.y);\n"
  "\n"
  "    tc = (aPos + 1) / 2;\n"
  "\n"
  "    gl_Position = vec4(pos, 0.0, 1.0); // see how we directly give a vec3 to vec4's constructor\n"
  "\n"
  "}";

const char* field_shader_fs = ""
  "#version 330 core\n"
  "out vec4 FragColor;\n"
  "  \n"
  "in vec2 tc;\n"
  "\n"
  "uniform sampler2D ourTexture;\n"
  "\n"
  "uniform float hue_shift;\n"
  "\n"
  "\n"
  "vec3 hueShift( vec3 color, float hueAdjust ){\n"
  "\n"
  "    const vec3  kRGBToYPrime = vec3 (0.299, 0.587, 0.114);\n"
  "    const vec3  kRGBToI      = vec3 (0.596, -0.275, -0.321);\n"
  "    const vec3  kRGBToQ      = vec3 (0.212, -0.523, 0.311);\n"
  "\n"
  "    const vec3  kYIQToR     = vec3 (1.0, 0.956, 0.621);\n"
  "    const vec3  kYIQToG     = vec3 (1.0, -0.272, -0.647);\n"
  "    const vec3  kYIQToB     = vec3 (1.0, -1.107, 1.704);\n"
  "\n"
  "    float   YPrime  = dot (color, kRGBToYPrime);\n"
  "    float   I       = dot (color, kRGBToI);\n"
  "    float   Q       = dot (color, kRGBToQ);\n"
  "    float   hue     = atan (Q, I);\n"
  "    float   chroma  = sqrt (I * I + Q * Q);\n"
  "\n"
  "    hue += hueAdjust;\n"
  "\n"
  "    Q = chroma * sin (hue);\n"
  "    I = chroma * cos (hue);\n"
  "\n"
  "    vec3    yIQ   = vec3 (YPrime, I, Q);\n"
  "\n"
  "    return vec3( dot (yIQ, kYIQToR), dot (yIQ, kYIQToG), dot (yIQ, kYIQToB) );\n"
  "\n"
  "}\n"
  "\n"
  "void main()\n"
  "{\n"
  "    vec4 textr = texture(ourTexture, tc);\n"
  "    if (textr[3] > 0.5) {\n"
  "        FragColor = vec4(hueShift(textr.rgb, hue_shift),1.0f);\n"
  "    }\n"
  "    else {\n"
  "        discard;\n"
  "    }\n"
  "}";
